# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_RadiationReceiver_0_0/HaccPL_RadiationReceiver_0_0.xci
# IP: The module: 'HaccPL_RadiationReceiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_1024_16/BRAM_1024_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_1024_16 || ORIG_REF_NAME==BRAM_1024_16} -quiet] -quiet

# IP: C:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_16384_32/BRAM_16384_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_16384_32 || ORIG_REF_NAME==BRAM_16384_32} -quiet] -quiet

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_1024_16/BRAM_1024_16_ooc.xdc

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_16384_32/BRAM_16384_32_ooc.xdc

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_RadiationReceiver_0_0/HaccPL_RadiationReceiver_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HaccPL_RadiationReceiver_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_RadiationReceiver_0_0/HaccPL_RadiationReceiver_0_0.xci
# IP: The module: 'HaccPL_RadiationReceiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_1024_16/BRAM_1024_16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_1024_16 || ORIG_REF_NAME==BRAM_1024_16} -quiet] -quiet

# IP: C:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_16384_32/BRAM_16384_32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_16384_32 || ORIG_REF_NAME==BRAM_16384_32} -quiet] -quiet

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_1024_16/BRAM_1024_16_ooc.xdc

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/ip/BRAM_16384_32/BRAM_16384_32_ooc.xdc

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_RadiationReceiver_0_0/HaccPL_RadiationReceiver_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HaccPL_RadiationReceiver_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
