# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_auto_pc_0/HaccPL_auto_pc_0.xci
# IP: The module: 'HaccPL_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_auto_pc_0/HaccPL_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HaccPL_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_auto_pc_0/HaccPL_auto_pc_0.xci
# IP: The module: 'HaccPL_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/HaccArcticFox/VivadoProject/HaccPL.srcs/sources_1/bd/HaccPL/ip/HaccPL_auto_pc_0/HaccPL_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HaccPL_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
