# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/HaccArcticFox/VivadoProject/Constraints/ZyboTest.xdc

# IP: ip/BRAM_1024_16/BRAM_1024_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_1024_16 || ORIG_REF_NAME==BRAM_1024_16} -quiet] -quiet

# IP: ip/BRAM_16384_32/BRAM_16384_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_16384_32 || ORIG_REF_NAME==BRAM_16384_32} -quiet] -quiet

# Block Designs: bd/HaccPL/HaccPL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL || ORIG_REF_NAME==HaccPL} -quiet] -quiet

# IP: bd/HaccPL/ip/HaccPL_processing_system7_0_0/HaccPL_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL_processing_system7_0_0 || ORIG_REF_NAME==HaccPL_processing_system7_0_0} -quiet] -quiet

# IP: bd/HaccPL/ip/HaccPL_RadiationReceiver_0_0/HaccPL_RadiationReceiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL_RadiationReceiver_0_0 || ORIG_REF_NAME==HaccPL_RadiationReceiver_0_0} -quiet] -quiet

# IP: ip/BRAM_1024_16/BRAM_1024_16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_1024_16 || ORIG_REF_NAME==BRAM_1024_16} -quiet] -quiet

# IP: ip/BRAM_16384_32/BRAM_16384_32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_16384_32 || ORIG_REF_NAME==BRAM_16384_32} -quiet] -quiet

# IP: bd/HaccPL/ip/HaccPL_ps7_0_axi_periph_0/HaccPL_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL_ps7_0_axi_periph_0 || ORIG_REF_NAME==HaccPL_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HaccPL/ip/HaccPL_rst_ps7_0_50M_0/HaccPL_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL_rst_ps7_0_50M_0 || ORIG_REF_NAME==HaccPL_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/HaccPL/ip/HaccPL_xlconcat_0_0/HaccPL_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL_xlconcat_0_0 || ORIG_REF_NAME==HaccPL_xlconcat_0_0} -quiet] -quiet

# IP: bd/HaccPL/ip/HaccPL_auto_pc_0/HaccPL_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HaccPL_auto_pc_0 || ORIG_REF_NAME==HaccPL_auto_pc_0} -quiet] -quiet

# XDC: ip/BRAM_1024_16/BRAM_1024_16_ooc.xdc

# XDC: ip/BRAM_16384_32/BRAM_16384_32_ooc.xdc

# XDC: ip/BRAM_1024_16/BRAM_1024_16_ooc.xdc

# XDC: ip/BRAM_16384_32/BRAM_16384_32_ooc.xdc

# XDC: bd/HaccPL/HaccPL_ooc.xdc
